login:
  oauth:
    - module: login.jwt
      options:
        audience: 35aacb63-777d-4320-9905-92a106af4558
        jwks:
          uri: https://majorleaguemirukenauthdev.b2clogin.com/majorleaguemirukenauthdev.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1a_signup_signin

