login:
  oauth:
    - module: login.jwt
      options:
        jwks:
          uri: https://teamsrvidentitydev.b2clogin.com/teamsrvidentitydev.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1a_signup_signin

