Databases:
  Azure:
    Name: adb2c
    Containers:
      - Name: subject
        PartitionKey:
          Paths:
            - /id
      - Name: principal
        PartitionKey:
          Paths:
            - /scope
        UniqueKeys:
          UniqueKeys:
            - Paths:
              - /type
              - /name