name: build adb2c auth srv

on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop"]
    paths:
    - 'adb2c/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'adb2c/**'
  repository_dispatch:
    types: [updated-miruken-dependencies]

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1712157679
      env:
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        ghToken:                        ${{ secrets.WORKFLOW_GH_TOKEN }}
        GH_TOKEN:                       ${{ secrets.WORKFLOW_GH_TOKEN }}
        repository:                     ${{ github.repository }}
        repositoryOwner:                ${{ github.repository_owner }}
        ref:                            ${{ github.event.client_payload.ref || github.ref }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
        ref:         ${{ github.event.client_payload.ref || github.ref }}
        fetch-depth: 0
        submodules: 'recursive'
    - name: npm ci
      working-directory: ./deployment/src
      run: npm ci
    - name: Run buildAdb2cAuthSrv.js
      run:  node ./deployment/src/buildAdb2cAuthSrv.js 
