name: build teamapi

on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop"]
    paths:
    - 'team-api/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'team-api/**'

permissions:
  contents: write

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        env:                            notused
        ghToken:                        ${{ secrets.WORKFLOW_GH_TOKEN }}
        GH_TOKEN:                       ${{ secrets.WORKFLOW_GH_TOKEN }}
        repositoryPath:                 ${{ github.workspace }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Run buildTeamApi.js
      run:  node ./deployment/src/buildTeamApi.js 
