name: build default container images

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "main", "develop"]
    paths:
    - 'default-container-image/**'

permissions:
  contents: write

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1712157679
      env:
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        GH_TOKEN:                       ${{ secrets.WORKFLOW_GH_TOKEN }}
        repository:                     ${{ github.repository }}
        repositoryOwner:                ${{ github.repository_owner }}

    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: 'recursive'
    - working-directory: ./default-container-image/cicd
      run: |
        npm ci
        npm run build
