name: build team

on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop"]
    paths:
    - 'team/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'team/**'
  repository_dispatch:
    types: [updated-team-dependencies]

permissions:
  contents: write

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        ghToken:                        ${{ secrets.WORKFLOW_GH_TOKEN }}
        GH_TOKEN:                       ${{ secrets.WORKFLOW_GH_TOKEN }}
        repositoryPath:                 ${{ github.workspace }}
        repository:                     ${{ github.repository }}
        repositoryOwner:                ${{ github.repository_owner }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
        submodules: 'recursive'
    - name: npm ci
      working-directory: ./deployment/src
      run: npm ci
    - name: Run buildTeam.js
      run:  node ./deployment/src/buildTeam.js 
