name: build pipeline

on:
  push:
    branches: [ "main", "develop"]
    paths:
    - 'teamapi/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'teamapi/**'

permissions:
  contents: write

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - name: Run build
      run: ./build-teamapi.sh
