name: build default container images

on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop"]
    paths:
    - 'defaultContainerImage/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'defaultContainerImage/**'

permissions:
  contents: write

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        ghToken:                        ${{ secrets.WORKFLOW_GH_TOKEN }}
        GH_TOKEN:                       ${{ secrets.WORKFLOW_GH_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        submodules: 'recursive'
    - name: npm ci
      working-directory: ./deployment/src
      run: npm ci
    - name: Run buildDefaultContainerImages.js 
      run:  node ./deployment/src/buildDefaultContainerImages.js
