name: build teamsrv

on:
  push:
    branches: [ "main", "develop"]
    paths:
    - 'teamsrv/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'teamsrv/**'

permissions:
  contents: write

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    env:
      TENANT_ID:                         ${{ vars.TENANT_ID }}
      DEPLOYMENT_PIPELINE_CLIENT_ID:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
      DEPLOYMENT_PIPELINE_CLIENT_SECRET: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
      GH_TOKEN:                          ${{ secrets.WORKFLOW_GH_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run build
      run: ./build-teamsrv.sh
