name: Run in a container

on: workflow_dispatch

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      env:
        ENV: dev
    steps:
    - name: Display Operating System Info
      run:  cat /etc/os-release
    - name: Print Working Directory
      run:  pwd
    - name: List directory
      run:  ls -la
