name: debug on container 

on:
  workflow_dispatch:
  push:
    branches: [ "debug"]

permissions:
  contents: write

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1689281138

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: pwd 
      run:  pwd 
    - name: ls
      run:  ls -la 

    - name: docker with dockerd and sleep 
      run:  (dockerd &) && (sleep 3; docker run --rm -v $(pwd):$(pwd) -v /var/run/docker.sock:/var/run/docker.sock --workdir $(pwd) alpine:latest ls -la)


