name: debug 

on:
  workflow_dispatch:
  push:
    branches: [ "debug"]

permissions:
  contents: write

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1689281138
      env:
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        env:                            notused
        ghToken:                        ${{ secrets.WORKFLOW_GH_TOKEN }}
        GH_TOKEN:                       ${{ secrets.WORKFLOW_GH_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: pwd 
      run:  pwd 
    - name: ls
      run:  ls -la 
    - name: Debug 
      run:  docker run --rm -v $(pwd):$(pwd) --workdir $(pwd) alpine:latest pwd
