name: deploy league to env
run-name: deploy to ${{ inputs.env || github.event.client_payload.env }} ${{ inputs.instance || github.event.client_payload.instance }}

on: 
  workflow_call:
    inputs:
      env:
        type:     string
        required: true
      instance:
        type:     string
        required: false
      schedule-srv-tag:
        description: 'schedule-srv Docker tag'
        required: false
        type: string
      tournament-srv-tag:
        description: 'tournament-srv Docker tag'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev 
        - qa
        - staging
        - demo
        - prod
      instance:
        description: 'Optional unique instance in an environment'
        default: ''
        required: false
        type: string
      schedule-srv-tag:
        description: 'schedule-srv Docker tag'
        required: false
        type: string
      tournament-srv-tag:
        description: 'tournament-srv Docker tag'
        required: false
        type: string

jobs:

  provision:
    name: provision ${{ inputs.env }} ${{ inputs.instance }}
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        repository:                     ${{ github.repository }}
        repositoryOwner:                ${{ github.repository_owner }}
        ref:                            ${{ github.event.client_payload.ref || github.ref }}
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        ghToken:                        ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN:                       ${{ secrets.GITHUB_TOKEN }}
        env:                            ${{ inputs.env      || github.event.client_payload.env }}
        instance:                       ${{ inputs.instance || github.event.client_payload.instance }}
        tag:                            ''
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref:        ${{ github.event.client_payload.ref || github.ref }}
        submodules: 'recursive'
    - name: npm run
      working-directory: ./league/cicd
      run: |
        npm ci
        npm run provision

  schedule-srv:
    name: schedule-srv ${{ inputs.env }} ${{ inputs.instance }}
    needs: provision
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        repository:                     ${{ github.repository }}
        repositoryOwner:                ${{ github.repository_owner }}
        ref:                            ${{ github.event.client_payload.ref || github.ref }}
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        ghToken:                        ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN:                       ${{ secrets.GITHUB_TOKEN }}
        env:                            ${{ inputs.env              || github.event.client_payload.env }}
        instance:                       ${{ inputs.instance         || github.event.client_payload.instance }}
        tag:                            ${{ inputs.schedule-srv-tag || github.event.client_payload.schedule-srv-tag }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref:        ${{ github.event.client_payload.ref || github.ref }}
        submodules: 'recursive'
    - name: npm run
      working-directory: ./league/schedule-srv/cicd
      run: |
        npm ci
        npm run deploy

  tournament-srv:
    name: tournament-srv ${{ inputs.env }} ${{ inputs.instance }}
    needs: provision
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        repository:                     ${{ github.repository }}
        repositoryOwner:                ${{ github.repository_owner }}
        ref:                            ${{ github.event.client_payload.ref || github.ref }}
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        ghToken:                        ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN:                       ${{ secrets.GITHUB_TOKEN }}
        env:                            ${{ inputs.env                || github.event.client_payload.env }}
        instance:                       ${{ inputs.instance           || github.event.client_payload.instance }}
        tag:                            ${{ inputs.tournament-srv-tag || github.event.client_payload.tournament-srv-tag }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref:        ${{ github.event.client_payload.ref || github.ref }}
        submodules: 'recursive'
    - name: npm run
      working-directory: ./league/tournament-srv/cicd
      run: |
        npm ci
        npm run deploy
