name: Deploy teamsrv

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag of the teamsrv'
        required: true
        type: string
      env:
        type: choice
        description: Environment
        options: 
        - dev 
        - qa
        - staging
        - demo
        - prod
      instance:
        description: 'Optional unique instance in an environment'
        default: ''
        required: false
        type: string

jobs:
  deploy-teamsrv:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1688663645
      env:
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        env:                            ${{ inputs.env }}
        instance:                       ${{ inputs.instance }}
        tag:                            ${{ inputs.tag }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: debug4
      run:  node --version
    - name: debug3
      run:  az --version
    - name: debug2
      run:  cat /etc/os-release
    - name: debug1
      run:  HOME=/root az containerapp --help    
    - name: deploy-teamsrv
      run:  HOME=/root node ./deployment/src/deployTeamsrv.js
