name: Deploy adb2c-api-connector-srv

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag of the team-srv'
        required: true
        type: string
      env:
        type: choice
        description: Environment
        options: 
        - dev 
        - qa
        - staging
        - demo
        - prod
      instance:
        description: 'Optional unique instance in an environment'
        default: ''
        required: false
        type: string

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        env:                            ${{ inputs.env }}
        instance:                       ${{ inputs.instance }}
        tag:                            ${{ inputs.tag }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: npm ci
      working-directory: ./deployment/src
      run: npm ci
    - name: Run deployAdb2cApiConnectorSrv.js
      run:  node ./deployment/src/deployAdb2cApiConnectorSrv.js
