name: deploy team-srv

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        type: string
      env:
        type: choice
        description: Environment
        options: 
        - dev 
        - qa
        - staging
        - demo
        - prod
      instance:
        description: 'Optional unique instance in an environment'
        default: ''
        required: false
        type: string
  repository_dispatch:
    types: [built-team-srv]

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        repository:                     ${{ github.repository }}
        repositoryOwner:                ${{ github.repository_owner }}
        ref:                            ${{ github.event.client_payload.ref || github.ref }}
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        ghToken:                        ${{ secrets.WORKFLOW_GH_TOKEN }}
        GH_TOKEN:                       ${{ secrets.WORKFLOW_GH_TOKEN }}
        env:                            ${{ inputs.env      || github.event.client_payload.env }}
        instance:                       ${{ inputs.instance || github.event.client_payload.instance }}
        tag:                            ${{ inputs.tag      || github.event.client_payload.tag }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref:        ${{ github.event.client_payload.ref || github.ref }}
        submodules: 'recursive'
    - name: npm ci
      working-directory: ./deployment/src
      run: npm ci
    - name: Run deployTeamsrv.js
      run:  node --trace-uncaught ./deployment/src/deployTeamsrv.js
