name: provision domain environment instance resources

on: 
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev 
        - qa
        - uat
        - demo
        - prod
        - dr
      instance:
        description: 'Optional unique instance in an environment'
        default: ''
        required: false
        type: string

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        env:                            ${{ inputs.env }}
        instance:                       ${{ inputs.instance }}
        ghToken:                        ${{ secrets.WORKFLOW_GH_TOKEN }}
        GH_TOKEN:                       ${{ secrets.WORKFLOW_GH_TOKEN }}
        repository:                     ${{ github.repository }}
        repositoryOwner:                ${{ github.repository_owner }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: npm ci
      working-directory: ./deployment/src
      run: npm ci
    - name: Run provisionDomainEnvironmentInstanceResources.js 
      run: node ./deployment/src/provisionDomainEnvironmentInstanceResources.js
