name: provision all resources

on: 
  workflow_dispatch:

jobs:
  provision-organization-global-resources:
    uses: ./.github/workflows/provision-organization-global-resources.yml
    with:
    secrets: inherit
