name: provision organization environment manual resource configuration

on: 
  workflow_call:
    inputs:
      env:
        type:     string
        required: true
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev 
        - qa
        - uat
        - demo
        - prod
        - dr

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        env:                            ${{ inputs.env }}
        ghToken:                        ${{ secrets.WORKFLOW_GH_TOKEN }}
        GH_TOKEN:                       ${{ secrets.WORKFLOW_GH_TOKEN }}
        repository:                     ${{ github.repository }}
        repositoryOwner:                ${{ github.repository_owner }}
        ref:                            ${{ github.event.client_payload.ref || github.ref }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref:        ${{ github.event.client_payload.ref || github.ref }}
        submodules: 'recursive'
    - name: npm ci
      working-directory: ./deployment/src
      run: npm ci
    - name: Run provisionOrganizationEnvironmentManualResourceConfiguration.js
      run: node ./deployment/src/provisionOrganizationEnvironmentManualResourceConfiguration.js
