name: provision organization environment common resources

on: 
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev 
        - qa
        - uat
        - demo
        - prod
        - dr

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        env:                            ${{ inputs.env }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Run provisionOrganizationEnvironmentCommonResources.js 
      run:  node ./deployment/src/provisionOrganizationEnvironmentCommonResources.js
