name: update team-api dependencies

on:
  workflow_dispatch:
    inputs:
      mirukenVersion:
        description: 'version of miruken'
        required: true
        type: string
  repository_dispatch:
    types: [built-miruken]

permissions:
  contents: write

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        ghToken:                        ${{ secrets.WORKFLOW_GH_TOKEN }}
        GH_TOKEN:                       ${{ secrets.WORKFLOW_GH_TOKEN }}
        mirukenVersion:                 ${{ inputs.mirukenVersion || github.event.client_payload.mirukenVersion }}
        repository:                     ${{ github.repository }}
        repositoryOwner:                ${{ github.repository_owner }}
        ref:                            ${{ github.event.client_payload.ref || github.ref }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref:        'refs/heads/develop'
        submodules: 'recursive'
    - name: npm ci
      working-directory: ./deployment/src
      run: npm ci
    - name: Run updateTeamApiDependencies.js
      run:  node ./deployment/src/updateMiruken.js 
