name: update team dependencies

on:
  workflow_dispatch:
    inputs:
      mirukenVersion:
        description: 'version of miruken'
        required: true
        type: string
      teamapiVersion:
        description: 'version of teamapi'
        required: true
        type: string
  repository_dispatch:
    types: [built-team-api]

permissions:
  contents: write

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        tenantId:                       ${{ vars.TENANT_ID }}
        subscriptionId:                 ${{ vars.SUBSCRIPTION_ID }}
        deploymentPipelineClientId:     ${{ vars.DEPLOYMENT_PIPELINE_CLIENT_ID }}
        deploymentPipelineClientSecret: ${{ secrets.DEPLOYMENT_PIPELINE_CLIENT_SECRET }}
        ghToken:                        ${{ secrets.WORKFLOW_GH_TOKEN }}
        GH_TOKEN:                       ${{ secrets.WORKFLOW_GH_TOKEN }}
        mirukenVersion:                 ${{ inputs.mirukenVersion || github.event.client_payload.mirukenVersion }}
        teamapiVersion:                 ${{ inputs.teamapiVersion || github.event.client_payload.teamapiVersion}}
        repository:                     ${{ github.repository }}
        repositoryOwner:                ${{ github.repository_owner }}
        ref:                            ${{ github.event.client_payload.ref || github.ref }}

    steps:
    - name: Debug
      run: |
        echo: "ref:                             [$ref]"
        echo: "github.event.client_payload.ref: [${{github.event.client_payload.ref}}]"
        echo: "github.ref:                      [${{ github.ref }}]"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref:        ${{ env.ref }} 
        submodules: 'recursive'
    - name: npm ci
      working-directory: ./deployment/src
      run: npm ci
    - name: Run updateTeamDependencies.js
      run:  node ./deployment/src/updateTeamDependencies.js 
